/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ifpb.projetopoo.view;

import com.ifpb.projetopoo.dao.AtendenteDAO;
import com.ifpb.projetopoo.model.Atendente;
import com.ifpb.projetopoo.model.Contato;
import com.ifpb.projetopoo.model.Endereco;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author IGOR
 */
public class Tela_Atualizar_Atendente extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro_Atendente
     */
    private Atendente atendente;
    private final AtendenteDAO dao;
    private final DateTimeFormatter fm;

    public Tela_Atualizar_Atendente() {
        fm = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        dao = new AtendenteDAO();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public Tela_Atualizar_Atendente(Atendente atendente) {
        fm = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        dao = new AtendenteDAO();
        this.atendente = atendente;
        initComponents();
        preencherCampos();
        campoCpf.setEnabled(false);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left_Menu = new javax.swing.JPanel();
        Text_1 = new javax.swing.JLabel();
        Text_2 = new javax.swing.JLabel();
        Text_3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Right_Menu4 = new javax.swing.JPanel();
        Usuario44 = new javax.swing.JLabel();
        Senha4 = new javax.swing.JLabel();
        CPF4 = new javax.swing.JLabel();
        Usuario45 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        campoSenha = new javax.swing.JPasswordField();
        campoCpf = new javax.swing.JFormattedTextField();
        Usuario46 = new javax.swing.JLabel();
        Usuario47 = new javax.swing.JLabel();
        Usuario48 = new javax.swing.JLabel();
        Usuario49 = new javax.swing.JLabel();
        btnCadastrar4 = new javax.swing.JButton();
        btnVoltar4 = new javax.swing.JButton();
        Usuario50 = new javax.swing.JLabel();
        campoDataDeAdmissao = new javax.swing.JFormattedTextField();
        campoNome = new javax.swing.JTextField();
        campoNascimento = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        Usuario52 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JFormattedTextField();
        campoEmail1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");

        Left_Menu.setBackground(new java.awt.Color(36, 37, 42));
        Left_Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(0, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        Text_1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Text_1.setForeground(new java.awt.Color(241, 231, 254));
        Text_1.setText("Cadastro");

        Text_2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Text_2.setForeground(new java.awt.Color(241, 231, 254));
        Text_2.setText("de");

        Text_3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Text_3.setForeground(new java.awt.Color(241, 231, 254));
        Text_3.setText(" Atendente");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Left_MenuLayout = new javax.swing.GroupLayout(Left_Menu);
        Left_Menu.setLayout(Left_MenuLayout);
        Left_MenuLayout.setHorizontalGroup(
            Left_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_MenuLayout.createSequentialGroup()
                .addGroup(Left_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Left_MenuLayout.createSequentialGroup()
                        .addGroup(Left_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Left_MenuLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(Text_1))
                            .addGroup(Left_MenuLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(Text_2))
                            .addGroup(Left_MenuLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Text_3)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(Left_MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Left_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        Left_MenuLayout.setVerticalGroup(
            Left_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_MenuLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Right_Menu4.setBackground(new java.awt.Color(102, 51, 153));

        Usuario44.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario44.setForeground(new java.awt.Color(241, 231, 254));
        Usuario44.setText("Usuario:");

        Senha4.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Senha4.setForeground(new java.awt.Color(241, 231, 254));
        Senha4.setText("Senha:");

        CPF4.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        CPF4.setForeground(new java.awt.Color(241, 231, 254));
        CPF4.setText("CPF:");

        Usuario45.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario45.setForeground(new java.awt.Color(241, 231, 254));
        Usuario45.setText("Nome:");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setToolTipText("");

        campoSenha.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhacampoSenhaActionPerformed(evt);
            }
        });

        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCpf.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        Usuario46.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario46.setForeground(new java.awt.Color(241, 231, 254));
        Usuario46.setText("Data de Nascimento:");

        Usuario47.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario47.setForeground(new java.awt.Color(241, 231, 254));
        Usuario47.setText("Email:");

        Usuario48.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario48.setForeground(new java.awt.Color(241, 231, 254));
        Usuario48.setText("Telefone:");

        Usuario49.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        Usuario49.setForeground(new java.awt.Color(241, 231, 254));
        Usuario49.setText("Informações");

        btnCadastrar4.setBackground(new java.awt.Color(241, 231, 254));
        btnCadastrar4.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        btnCadastrar4.setText("Atualizar");
        btnCadastrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar4btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar4.setBackground(new java.awt.Color(241, 231, 254));
        btnVoltar4.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        btnVoltar4.setText("Voltar");
        btnVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar4btnVoltarActionPerformed(evt);
            }
        });

        Usuario50.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario50.setForeground(new java.awt.Color(241, 231, 254));
        Usuario50.setText("Data de Admissão:");

        try {
            campoDataDeAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataDeAdmissao.setText("dd/mm/aaaa   ");
        campoDataDeAdmissao.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoDataDeAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataDeAdmissaocampoDataDeAdmissaoActionPerformed(evt);
            }
        });

        campoNome.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomecampoNomeActionPerformed(evt);
            }
        });

        campoNascimento.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNascimentocampoEmailActionPerformed(evt);
            }
        });

        campoEndereco.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecocampoRuaActionPerformed(evt);
            }
        });

        Usuario52.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Usuario52.setForeground(new java.awt.Color(241, 231, 254));
        Usuario52.setText("Endereço: ");

        campoUsuario.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuariocampoUsuarioActionPerformed(evt);
            }
        });

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        campoEmail1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        campoEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmail1campoEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Right_Menu4Layout = new javax.swing.GroupLayout(Right_Menu4);
        Right_Menu4.setLayout(Right_Menu4Layout);
        Right_Menu4Layout.setHorizontalGroup(
            Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_Menu4Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(Usuario49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Right_Menu4Layout.createSequentialGroup()
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Senha4)
                            .addComponent(Usuario44))
                        .addGap(37, 37, 37)
                        .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoSenha)
                            .addComponent(campoUsuario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_Menu4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoEndereco)
                            .addGroup(Right_Menu4Layout.createSequentialGroup()
                                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                                        .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Usuario45)
                                            .addComponent(Usuario52)
                                            .addComponent(Usuario46)
                                            .addComponent(Usuario48))
                                        .addGap(0, 186, Short.MAX_VALUE))
                                    .addComponent(campoNome)
                                    .addComponent(campoTelefone)
                                    .addComponent(campoNascimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                                        .addGap(0, 141, Short.MAX_VALUE)
                                        .addComponent(btnVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCadastrar4))
                                    .addComponent(campoDataDeAdmissao)
                                    .addComponent(campoCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                                        .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CPF4)
                                            .addComponent(Usuario50)
                                            .addComponent(Usuario47))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Right_Menu4Layout.createSequentialGroup()
                    .addGap(571, 571, 571)
                    .addComponent(campoEmail1)
                    .addGap(31, 31, 31)))
        );
        Right_Menu4Layout.setVerticalGroup(
            Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_Menu4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right_Menu4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Usuario44))
                .addGap(18, 18, 18)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha4)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario49)
                .addGap(31, 31, 31)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario45)
                    .addComponent(CPF4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario46)
                    .addComponent(Usuario47))
                .addGap(18, 18, 18)
                .addComponent(campoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario48)
                    .addComponent(Usuario50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataDeAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usuario52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(Right_Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Right_Menu4Layout.createSequentialGroup()
                    .addGap(371, 371, 371)
                    .addComponent(campoEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(395, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(Right_Menu4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Left_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(Left_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSenhacampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhacampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhacampoSenhaActionPerformed

    private void btnCadastrar4btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar4btnCadastrarActionPerformed
        // TODO add your handling code here:


        if (verificarCampos()) {
            if (dao.update(atendente.getCpf(),new Atendente(0, LocalDate.now(), campoCpf.getText(), campoNome.getText(), LocalDate.parse(campoNascimento.getText(), fm), campoUsuario.getText(), campoSenha.getText(), new Endereco(campoEndereco.getText(), "", "", ""), new Contato(campoNascimento.getText(), campoTelefone.getText())))) {
                JOptionPane.showMessageDialog(null, "Atendente atualizado com sucesso!");
                new Tela_Login_Atendente().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar atendente!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Algum campo obrigatório não foi preenchido!\nTodos os campos são obrigatórios menos o email.");
        }


    }//GEN-LAST:event_btnCadastrar4btnCadastrarActionPerformed

    private void btnVoltar4btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar4btnVoltarActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new Tela_Principal(atendente).setVisible(true);
    }//GEN-LAST:event_btnVoltar4btnVoltarActionPerformed

    private void campoDataDeAdmissaocampoDataDeAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataDeAdmissaocampoDataDeAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDeAdmissaocampoDataDeAdmissaoActionPerformed

    private void campoNomecampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomecampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomecampoNomeActionPerformed

    private void campoNascimentocampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNascimentocampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNascimentocampoEmailActionPerformed

    private void campoEnderecocampoRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecocampoRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecocampoRuaActionPerformed

    private void campoUsuariocampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuariocampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuariocampoUsuarioActionPerformed

    private void campoEmail1campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmail1campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmail1campoEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizar_Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizar_Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizar_Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizar_Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Atualizar_Atendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF4;
    private javax.swing.JPanel Left_Menu;
    private javax.swing.JPanel Right_Menu4;
    private javax.swing.JLabel Senha4;
    private javax.swing.JLabel Text_1;
    private javax.swing.JLabel Text_2;
    private javax.swing.JLabel Text_3;
    private javax.swing.JLabel Usuario44;
    private javax.swing.JLabel Usuario45;
    private javax.swing.JLabel Usuario46;
    private javax.swing.JLabel Usuario47;
    private javax.swing.JLabel Usuario48;
    private javax.swing.JLabel Usuario49;
    private javax.swing.JLabel Usuario50;
    private javax.swing.JLabel Usuario52;
    private javax.swing.JButton btnCadastrar4;
    private javax.swing.JButton btnVoltar4;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JFormattedTextField campoDataDeAdmissao;
    private javax.swing.JTextField campoEmail1;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables

    private boolean verificarCampos() {

        if (campoCpf.getText().equals("   .   .   -  ") || campoDataDeAdmissao.getText().equals("  /  /    ")
                || campoNascimento.equals("  /  /    ") || campoNome.getText().length() == 0 || campoEndereco.getText().length() == 0 || campoSenha.getText().length() == 0
                || campoTelefone.getText().length() == 0 || campoUsuario.getText().length() == 0) {

            return false;

        }

        return true;
    }
    
    private void preencherCampos() {
        
        LocalDate data = atendente.getNascimento();
        
        LocalDate parsedDate = LocalDate.parse(data.format(fm), fm);
        campoCpf.setText(atendente.getCpf());
        campoNascimento.setText(atendente.getContato().getEmail());
        campoNascimento.setText(parsedDate.toString());
        campoNome.setText(atendente.getNome());
        campoEndereco.setText(atendente.getEndereco().getRua());
        campoTelefone.setText(atendente.getContato().getTelefone());
        campoUsuario.setText(atendente.getUsuario());
        campoSenha.setText(atendente.getSenha());
        
    }
    
    
    
}
