CREATE TABLE Paciente(
	Cpf CHAR(14),
	Nome VARCHAR(100) NOT NULL,
	Nascimento DATE NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
	Email VARCHAR(100),
	Telefone VARCHAR(20) NOT NULL,
	PRIMARY KEY (Cpf)
)